apiVersion: v1
kind: ConfigMap
metadata:
  name: complaint-identity
data:
  CASE_CREATOR_UKVI_COMPLAINT_USER: {{.CASE_CREATOR_UKVI_COMPLAINT_USER}}
  CASE_CREATOR_UKVI_COMPLAINT_TEAM: {{.CASE_CREATOR_UKVI_COMPLAINT_TEAM}}
  CASE_CREATOR_UKVI_COMPLAINT_GROUP: {{.CASE_CREATOR_UKVI_COMPLAINT_GROUP}}
